<?php
return [
    'section' => [
        'id'     => '_ai_writer_settings',
        'label'  => __('sidebar.ai_writer_settings'),
        'tabs'          => true,
        'icon'   => '',
    ],
    'fields' => [
        [
            'id'            => 'enable_on_profile_settings',
            'type'          => 'switch',
            'tab_id'        => 'profile_setting',
            'tab_title'     => __('settings.profile'),
            'class'         => '',
            'label_title'   => __('settings.enable_on_profile_settings'),
            'field_desc'    => __('settings.enable_on_profile_settings_desc'),
            'value'         => '1',
        ],
        [
            'id'            => 'profile_prompt',
            'type'          => 'textarea',
            'tab_id'        => 'profile_setting',
            'tab_title'     => __('settings.profile'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.profile_prompt'),
            'placeholder'   => __('settings.add_profile_prompt'),
        ],

        [
            'id'            => 'enable_on_education_settings',
            'type'          => 'switch',
            'tab_id'        => 'resume_setting',
            'tab_title'     => __('settings.resume'),
            'class'         => '',
            'label_title'   => __('settings.enable_on_education_settings'),
            'field_desc'    => __('settings.enable_on_education_settings_desc'),
            'value'         => '1',
        ],
        [
            'id'            => 'education_prompt',
            'type'          => 'textarea',
            'tab_id'        => 'resume_setting',
            'tab_title'     => __('settings.resume'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.education_prompt'),
            'placeholder'   => __('settings.add_education_prompt'),
        ],
        [
            'id'            => 'enable_on_experience_settings',
            'type'          => 'switch',
            'tab_id'        => 'resume_setting',
            'tab_title'     => __('settings.resume'),
            'class'         => '',
            'label_title'   => __('settings.enable_on_experience_settings'),
            'field_desc'    => __('settings.enable_on_experience_settings_desc'),
            'value'         => '1',
        ],
        [
            'id'            => 'experience_prompt',
            'type'          => 'textarea',
            'tab_id'        => 'resume_setting',
            'tab_title'     => __('settings.resume'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.experience_prompt'),
            'placeholder'   => __('settings.add_experience_prompt'),
        ],
        [
            'id'            => 'enable_on_awards_settings',
            'type'          => 'switch',
            'tab_id'        => 'resume_setting',
            'tab_title'     => __('settings.resume'),
            'class'         => '',
            'label_title'   => __('settings.enable_on_awards_settings'),
            'field_desc'    => __('settings.enable_on_awards_settings_desc'),
            'value'         => '1',
        ],
        [
            'id'            => 'awards_prompt',
            'type'          => 'textarea',
            'tab_id'        => 'resume_setting',
            'tab_title'     => __('settings.resume'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.awards_prompt'),
            'placeholder'   => __('settings.add_awards_prompt'),
        ],
        [
            'id'            => 'enable_on_sessions_settings',
            'type'          => 'switch',
            'tab_id'        => 'sessions_setting',
            'tab_title'     => __('settings.sessions'),
            'class'         => '',
            'label_title'   => __('settings.enable_on_sessions_settings'),
            'field_desc'    => __('settings.enable_on_sessions_settings_desc'),
            'value'         => '1',
        ],
        [
            'id'            => 'sessions_prompt',
            'type'          => 'textarea',
            'tab_id'        => 'sessions_setting',
            'tab_title'     => __('settings.sessions'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.sessions_prompt'),
            'placeholder'   => __('settings.add_sessions_prompt'),
        ],
        [
            'id'            => 'enable_on_slots_settings',
            'type'          => 'switch',
            'tab_id'        => 'sessions_setting',
            'tab_title'     => __('settings.sessions'),
            'class'         => '',
            'label_title'   => __('settings.enable_on_slots_settings'),
            'field_desc'    => __('settings.enable_on_slots_settings_desc'),
            'value'         => '1',
        ],
        [
            'id'            => 'slots_prompt',
            'type'          => 'textarea',
            'tab_id'        => 'sessions_setting',
            'tab_title'     => __('settings.sessions'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.slots_prompt'),
            'placeholder'   => __('settings.add_slots_prompt'),
        ],
        
        [
            'id'            => 'enable_on_resch_sessions_settings',
            'type'          => 'switch',
            'tab_id'        => 'sessions_setting',
            'tab_title'     => __('settings.sessions'),
            'class'         => '',
            'label_title'   => __('settings.enable_on_resch_sessions_settings'),
            'field_desc'    => __('settings.enable_on_resch_sessions_settings_desc'),
            'value'         => '1',
        ],
        [
            'id'            => 'reschedule_sessions_prompt',
            'type'          => 'textarea',
            'tab_id'        => 'sessions_setting',
            'tab_title'     => __('settings.sessions'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.reschedule_sessions_prompt'),
            'placeholder'   => __('settings.add_reschedule_sessions_prompt'),
        ],
    ]
];
