<?php
if (!\Nwidart\Modules\Facades\Module::has('s3konnect') || !\Nwidart\Modules\Facades\Module::isEnabled('s3konnect')) {
    return [];
}
return [
    'section' => [
        'id'     => '_storage',
        'label'  => __('s3konnect::s3konnect.s3_bucket_setting'),
        'icon'   => '',
    ],
    'fields' => [
        [
            'id'            => 's3_enabled',
            'type'          => 'switch',
            'tab_title'     => __('s3konnect::s3konnect.storage_settings'),
            'class'         => '',
            'label_title'   => __('s3konnect::s3konnect.s3_bucket_status'),
            'field_desc'    => __('s3konnect::s3konnect.s3_bucket_status_desc'),
            'value'         => 'on',
        ],
        [
            'id'            => 'access_key_id',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('s3konnect::s3konnect.access_key_id'),
            'placeholder'   => __('s3konnect::s3konnect.access_key_id_placeholder'),
        ],
        [
            'id'            => 'secret_access_key',
            'type'          => 'text',
            'value'         => '',
            'class'         => '',
            'label_title'   => __('s3konnect::s3konnect.secret_access_key'),
            'placeholder'   => __('s3konnect::s3konnect.secret_access_key_placeholder'),
        ],
        [
            'id'            => 'default_region',
            'type'          => 'select',
            'class'         => '',
            'label_title'   => __('s3konnect::s3konnect.default_region'),
            'field_desc'   => __('s3konnect::s3konnect.default_region_desc'),
            'options'       => [
                'us-east-2'             => 'US East (Ohio)',
                'us-east-1'             => 'US East (N. Virginia)',
                'us-west-1'             => 'US West (N. California)',
                'us-west-2'             => 'US West (Oregon)',
                'af-south-1'            => 'Africa (Cape Town)',
                'ap-east-1'             => 'Asia Pacific (Hong Kong)',
                'ap-south-2'            => 'Asia Pacific (Hyderabad)',
                'ap-southeast-3'        => 'Asia Pacific (Jakarta)',
                'ap-southeast-5'        => 'Asia Pacific (Malaysia)',
                'ap-southeast-4'        => 'Asia Pacific (Melbourne)',
                'ap-south-1'            => 'Asia Pacific (Mumbai)',
                'ap-northeast-3'        => 'Asia Pacific (Osaka)',
                'ap-northeast-2'        => 'Asia Pacific (Seoul)',
                'ap-southeast-1'        => 'Asia Pacific (Singapore)',
                'ap-southeast-2'        => 'Asia Pacific (Sydney)',
                'ap-northeast-1'        => 'Asia Pacific (Tokyo)',
                'ca-central-1'          => 'Canada (Central)',
                'ca-west-1'             => 'Canada West (Calgary)',
                'eu-central-1'          => 'Europe (Frankfurt)',
                'eu-west-1'             => 'Europe (Ireland)',
                'eu-west-2'             => 'Europe (London)',
                'eu-south-1'            => 'Europe (Milan)',
                'eu-west-3'             => 'Europe (Paris)',
                'eu-south-2'            => 'Europe (Spain)',
                'eu-north-1'            => 'Europe (Stockholm)',
                'eu-central-2'          => 'Europe (Zurich)',
                'il-central-1'          => 'Israel (Tel Aviv)',
                'me-south-1'            => 'Middle East (Bahrain)',
                'me-central-1'          => 'Middle East (UAE)',
                'sa-east-1'             => 'South America (São Paulo)',
                'us-gov-east-1'         => 'AWS GovCloud (US-East)',
                'us-gov-west-1'         => 'AWS GovCloud (US-West)',
            ],
        ],
        [
            'id'            => 'bucket_name',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('s3konnect::s3konnect.bucket_name'),
            'placeholder'   => __('s3konnect::s3konnect.bucket_name_placeholder'),
        ],

    ]
];
