<?php
return [
    'section' => [
       'id'     => '_theme', 
       'label'  => __('sidebar.theme_settings'), 
       'icon'   => '', 
    ],
    'fields' => [
        [
            'id'            => 'theme_pri_color',
            'type'          => 'colorpicker',
            'value'         => '#FCCF14',
            'class'         => '',
            'label_title'   => __('settings.theme_primary_color'),
            'field_desc'    => __('settings.theme_primary_color_desc'),
        ],
        [
            'id'            => 'theme_sec_color',
            'type'          => 'colorpicker',
            'value'         => '#FAF8F5',
            'class'         => '',
            'label_title'   => __('settings.theme_secondary_color'),
            'field_desc'    => __('settings.theme_secondary_color_desc'),
        ],
        [
            'id'            => 'theme_footer_bg',
            'type'          => 'colorpicker',
            'value'         => '#065A46',
            'class'         => '',
            'label_title'   => __('settings.theme_footer_bg'),
            'field_desc'    => __('settings.theme_footer_bg_desc'),
        ],
        [
            'id'            => 'theme_footer_text_color',
            'type'          => 'colorpicker',
            'value'         => '#fff',
            'class'         => '',
            'label_title'   => __('settings.theme_footer_text_color'),
            'field_desc'    => __('settings.theme_footer_text_color_desc'),
        ],
        [
            'id'            => 'auth_bg_color',
            'type'          => 'colorpicker',
            'value'         => '#FBF9F4',
            'class'         => '',
            'label_title'   => __('settings.auth_bg_color'),
            'field_desc'    => __('settings.auth_bg_color_desc'),
        ],
        // [
        //     'id'            => 'text_dark_color',
        //     'type'          => 'colorpicker',
        //     'value'         => '#0A0F26',
        //     'class'         => '',
        //     'label_title'   => __('settings.text_dark_color'),
        //     'field_desc'    => __('settings.text_dark_color_desc'),
        // ],
        [
            'id'            => 'text_light_color',
            'type'          => 'colorpicker',
            'value'         => '#585858',
            'class'         => '',
            'label_title'   => __('settings.text_light_color'),
            'field_desc'    => __('settings.text_light_color_desc'),
        ],
        // [
        //     'id'            => 'text_yellow_color',
        //     'type'          => 'colorpicker',
        //     'value'         => '#FCCF14',
        //     'class'         => '',
        //     'label_title'   => __('settings.text_yellow_color'),
        //     'field_desc'    => __('settings.text_yellow_color_desc'),
        // ],
        [
            'id'            => 'body_font_color',
            'type'          => 'colorpicker',
            'value'         => '#585858',
            'class'         => '',
            'label_title'   => __('settings.body_font_color'),
            'field_desc'    => __('settings.body_font_color_desc'),
        ],
        [
            'id'            => 'heading_color',
            'type'          => 'colorpicker',
            'value'         => '#000',
            'class'         => '',
            'label_title'   => __('settings.heading_color'),
            'field_desc'    => __('settings.heading_color_desc'),
        ],
        [
            'id'            => 'btn_white_color',
            'type'          => 'colorpicker',
            'value'         => '#fff',
            'class'         => '',
            'label_title'   => __('settings.btn_white_color'),
            'field_desc'    => __('settings.btn_white_color_desc'),
        ],
        [
            'id'            => 'btn_black_color',
            'type'          => 'colorpicker',
            'value'         => '#000',
            'class'         => '',
            'label_title'   => __('settings.btn_black_color'),
            'field_desc'    => __('settings.btn_black_color_desc'),
        ],
        [
            'id'            => 'btn_color',
            'type'          => 'colorpicker',
            'value'         => '#FCCF14',
            'class'         => '',
            'label_title'   => __('settings.btn_color'),
            'field_desc'    => __('settings.btn_color_desc'),
        ],
        [
            'id'            => 'btn_disable_color',
            'type'          => 'colorpicker',
            'value'         => '#f7f7f8',
            'class'         => '',
            'label_title'   => __('settings.btn_disable_color'),
            'field_desc'    => __('settings.btn_disable_color_desc'),
        ],
        [
            'id'            => 'btn_secondary_color',
            'type'          => 'colorpicker',
            'value'         => '#F55C2B',
            'class'         => '',
            'label_title'   => __('settings.btn_secondary_color'),
            'field_desc'    => __('settings.btn_secondary_color_desc'),
        ],
        // [
        //     'id'            => 'heading_color',
        //     'type'          => 'colorpicker',
        //     'value'         => '#000',
        //     'class'         => '',
        //     'label_title'   => __('settings.heading_color'),
        //     'field_desc'    => __('settings.heading_color_desc'),
        // ],
        // [
        //     'id'            => 'btn_bg_pri_color',
        //     'type'          => 'colorpicker',
        //     'value'         => '#FCCF14',
        //     'class'         => '',
        //     'label_title'   => __('settings.button_bg_pri_color'),
        //     'field_desc'    => __('settings.button_bg_pri_color_desc'),
        // ],
        // [
        //     'id'            => 'btn_bg_sec_color',
        //     'type'          => 'colorpicker',
        //     'value'         => '#0A0F26',
        //     'class'         => '',
        //     'label_title'   => __('settings.button_bg_sec_color'),
        //     'field_desc'    => __('settings.button_bg_sec_color'),
        // ],
        // [
        //     'id'            => 'link_color',
        //     'type'          => 'colorpicker',
        //     'value'         => '#1DA1F2',
        //     'class'         => '',
        //     'label_title'   => __('settings.link_color'),
        //     'field_desc'    => __('settings.link_color_desc'),
        // ],
        // [
        //     'id'            => 'btn_text_color',
        //     'type'          => 'colorpicker',
        //     'value'         => '#1C1C1C',
        //     'class'         => '',
        //     'label_title'   => __('settings.button_text_color'),
        // ],
        // [
        //     'id'            => 'header_text_color',
        //     'type'          => 'colorpicker',
        //     'value'         => '#1E1E1E',
        //     'class'         => '',
        //     'label_title'   => __('settings.header_text_color')
        // ],
    ]
];